<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Booking</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3d5063a6-5719-4947-92bf-1dbe07b230df</testSuiteGuid>
   <testCaseLink>
      <guid>2d9d1dcb-a32f-440f-a4d8-15f70ab0bf38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Booking page - Landing</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7a4a1a9a-ef4d-4e1e-bfed-1d5b2a8e323a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Booking page - Book ALL available cons for one carrier - no additional items</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>051a5af2-1ed6-4ae7-998d-e977f067831c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Booking page - Book ALL available cons for one carrier - with 1 additional item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc06ba19-c64d-4945-a5de-a75cdb1ef04a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e01d17d-a6f0-438d-a400-d25bd922364b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d5dce2d-b697-4274-b436-338bf4d5356e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6bd3f85-240d-4790-b2b6-e1878a651171</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed70048e-fba0-4b82-a897-1109dabc25b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f0cf749-b4fc-4368-9984-947de9de6481</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdc89df4-9d1a-4e0a-b3b6-c5053023f3dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d89eb0e1-9ef1-4e9f-95bc-dcfc0dee47db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Booking page - Book ONE available cons for one carrier - with 1 additional item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72e0e4c8-40a5-4334-952e-d1a471104c67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6642d40b-01ec-448a-948e-085968fc101f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5b863c0-096b-4969-9087-62c417bdef8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a55306e7-a797-4b06-9a3f-4c6dd2c8809a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb357647-cd62-42aa-b82b-84ddfad0b6e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>175c79fa-f0c6-4adc-81c0-8fd15dfdd772</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca98b4e4-e473-41ed-a771-483a22d1b077</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
