<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create Consignment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>1f6f8ab9-5522-4497-a127-42d3ba1ff949</testSuiteGuid>
   <testCaseLink>
      <guid>1fee84dd-e24c-456a-a989-5187aa6b1b2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Myfreight - New Consignment - existing receiver address 1 item no DG</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f41323-517f-4fab-b04d-8ef68c45ab93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b033bf31-225e-4cda-98ba-89be59cadf5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ed2cb49-b3ef-49d6-bc76-46ba13d45607</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1940fd6c-13cb-4ace-8d57-a15307f9ae88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d17cf5-019e-4ab1-a5a2-41a79c8280e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7434b6ac-88e8-4c44-b876-10fe70287ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e43af07-22b4-4c45-a788-bd124f8d59d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>061f89d4-4cd1-41ca-910a-ef9ae0c7fcf0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c29cd159-b05e-49c4-ae3e-a06268841308</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Myfreight - New Consignment - existing receiver address - 1 item with DG</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a66f597f-6628-4d30-adb0-50c2c58a7ec1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2464f7-d651-4bbc-9bdf-875a84106e1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6687689c-ac2e-489f-b665-d4b94d8e424c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0f258e7-89e2-4362-a1dc-62519891b6d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60b0c275-e70d-4d7c-8a7b-aad356ca1e2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33251433-84d2-4d49-92cc-b43c43d4960c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>106288a7-a899-4d6d-bca4-eb57bd10c2f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff4633ba-1446-4a93-9123-8a61ce60fbb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85088b5b-3317-490c-8683-b579d3596ab2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0caa6fd3-7b01-4de8-843c-092f0965c12d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Myfreight - New Consignment - existing receiver address - InvalidItemTypeInput</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3cd0fad-f3dc-4add-b8ce-351e1976c415</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>289150cc-0f42-45b6-b4b4-ecc5c7182307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd656959-4fa2-42a3-ad47-71663d4daa38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da457423-77e3-4b1a-a931-fe2934beb167</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38d4709f-9df4-47a3-8b0d-ac200c812fcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b94d6f33-6d7e-4c9f-82ad-7129baa22991</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>268e6e91-13aa-4e5a-8f26-c954cb193b1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>605f2323-d1f6-47bc-af8c-0fd8380c3266</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>abcee5a9-de21-44ec-8c81-9b5e2525cca4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Myfreight - New Consignment - new receiver address - 1 item no DG</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5ffcb3b-b565-486b-9b7f-d882e4791b8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dd094dc-9223-400f-b87c-deb76243cd1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72e3ca6d-6502-472d-a224-9f4a6a55b9fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d6114e4-d383-485a-a9c6-cadb859808a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f6e373b-3a0a-44f9-8eb9-299966fd55be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc7eb66-c354-49f7-8e65-2634d81b3a3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44167d8d-54e3-4c14-92dd-267bc044017b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1bb70e2-80c2-4c6a-8308-ad091b216f5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Myfreight - New Consignment - new receiver address - 1 item with DG</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5707b86c-f63d-4362-911d-b0af43acf2bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb2a75f1-9a50-4855-9c92-11ffaf05bae2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2dacc53-6b48-41e2-b4c5-aa28d423d224</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a378072e-0a74-4647-a4ed-78ec1076922c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f0ff6f6-ba42-4be0-9efe-112ce3590693</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3be06cc2-aeb9-481e-b9ae-d57fcce5a426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b4e51ce-3e69-46de-a4ff-1e4fdd10f7eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00ab74d2-3ec8-4946-97eb-acc6f2dc2376</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
