<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QTE15200531</name>
   <tag></tag>
   <elementGuidId>c9d638fa-1701-4491-a6df-a6113e4c4a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.ng-scope:nth-child(5) div.container:nth-child(1) div.ng-scope:nth-child(3) div.quotes.ng-scope div.row div.span24 div.row.item.ng-scope:nth-child(4) div.span24 div.row div.span3:nth-child(1) > a:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html[1]/body[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://qa.teamwilberforce.com/#/quote/15200531</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>once-text</name>
      <type>Main</type>
      <value>quote.id | quoteReference</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>once-href</name>
      <type>Main</type>
      <value>quote.url</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QTE15200531</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ng-app&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;quotes ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span24&quot;]/div[@class=&quot;row item ng-scope&quot;]/div[@class=&quot;span24&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span3&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
